version: "3"
services:
  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DOCKER_MYSQL_SPRINGBOOT_DEMO_MYSQL_HOST=docker-mysql-springboot-demo-db
      - DOCKER_MYSQL_SPRINGBOOT_DEMO_MYSQL_PORT=3306
    ports:
      - "8081:8081"
    networks:
      - app-network
    depends_on:
      - mysqlDb
    restart: on-failure
    command: ["./wait-for-it.sh", "mysqlDb:3306", "--", "java", "-jar", "your-app.jar"]

  mysqlDb:
    image: mysql:8.0.22
    container_name: docker-mysql-springboot-demo-db
    ports:
      - "3307:3306"
    networks:
      - app-network
    volumes:
      - volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: docker_mysql_springboot_demo
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

networks:
  app-network:
    driver: bridge

volumes:
  volume:
