version: "3"
services:
  springBootApp:
    image: uday07/docker-mysql-springboot-demo:latest
    container_name: docker-mysql-springboot-demo-app
    ports:
      - "8081:8081"
    networks:
      - network
    depends_on:
      - mysqlDb
    restart: on-failure

  mysqlDb:
    image: mysql:8.0.22
    container_name: docker-mysql-springboot-demo-db
    ports:
      - "3307:3306"
    networks:
      - network
    volumes:
      - volume:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD="true"

networks:
  network:

volumes:
  volume: