spring:
  datasource:
    url: jdbc:mysql://docker-mysql-springboot-demo-db:3306/docker_mysql_springboot_demo?createDatabaseIfNotExist=true
    username: root
    password:

  jpa:
    show-sql: true

    hibernate:
      ddl-auto: update

server:
  port: 8081

  error:
    include-message: always