spring:
  datasource:
    url: jdbc:mysql://localhost:3306/docker_mysql_springboot_demo?createDatabaseIfNotExist=true
    username: root
    password: root

  jpa:
    show-sql: true

    hibernate:
      ddl-auto: update